// GENERATED by tools/portgen/generate.py; edit the source, never this file. encryption.umsg sha256:d18065b66d55759c3bdf915c6fc3eba5c961db18108164093f3e30584bc4aaa8 program-v0.umsg sha256:60aa8718f2ca4b8c1ad859fc3128b7cde056a007c397d940c83a96596ab44bf8 generate.py sha256:8291dcc665ea3e88dacc2817bba654ff4fad06b1e980b22d07e0486b94f1cbcc runtime.py sha256:ad4c62c4259502960dda02e345bd597a8cee527986d79b8984bcaf475aea7677 runtime.js sha256:9da4d4edaa79fa494f4a28c3f4e8a8102a1ff2c0bf86a978810cd87e2f19d603 dart_backend.py sha256:08d9e62142d235d32510b3928c5a8434c3987d227f889b322d8ca50bc9c5d2a5 runtime.dart sha256:e8a2509da2273b37f6d8091568a8c920ce6227083d3b7d6129aa50463b930c66 java_backend.py sha256:e89c9b61a0ba2b5b57d8b4c1bc5bea64c3e84226a0005671eaa1189d645bcf34 runtime.java sha256:bd88f7d7e3d6cb9bfd7831e72c96d5867e995b108da4b48eca67de0d6c2ad411 rust_backend.py sha256:39d06b7d61ce55884f90cced7fe80803a03c1efe970f395a71ace6ea5975ccfc runtime.rs sha256:4080c448093ace2c59859b2bd04d662d9432352fad3385b8d0b17f61f987066d
// ignore_for_file: non_constant_identifier_names, unused_element, unused_local_variable, unnecessary_parenthesis
// General operations for the executable vocabulary; no UniMSG rules.
import 'dart:convert';
import 'dart:typed_data';

class ProgramError implements Exception {
  final String message;
  final BigInt offset;
  ProgramError(this.message, this.offset);
  @override
  String toString() => '$message at offset $offset';
}

void r_assert(dynamic test, dynamic message) {
  r_text(message);
  if (!r_bool(test)) throw ArgumentError(message);
}

void r_require(dynamic test, dynamic message, dynamic offset) {
  r_assert(r_int(offset) >= BigInt.zero, 'negative diagnostic offset');
  r_text(message);
  if (!r_bool(test)) throw ProgramError(message, offset);
}

BigInt r_int(dynamic x) {
  if (x is! BigInt) throw ArgumentError('expected integer');
  return x;
}

bool r_bool(dynamic x) {
  if (x is! bool) throw ArgumentError('expected boolean');
  return x;
}

List<dynamic> r_list(dynamic x) {
  if (x is! List || x is Uint8List) throw ArgumentError('expected list');
  return x;
}

String r_text(dynamic x) {
  if (x is! String) throw ArgumentError('expected text');
  return x;
}

Uint8List r_bytes(dynamic x) {
  if (x is! Uint8List) throw ArgumentError('expected bytes');
  return x;
}

dynamic r_add(dynamic a, dynamic b) => r_int(a) + r_int(b);
dynamic r_sub(dynamic a, dynamic b) => r_int(a) - r_int(b);
dynamic r_mul(dynamic a, dynamic b) => r_int(a) * r_int(b);
dynamic r_div(dynamic a, dynamic b) {
  r_assert(
    r_int(a) >= BigInt.zero && r_int(b) > BigInt.zero,
    'division domain',
  );
  return a ~/ b;
}

dynamic r_mod(dynamic a, dynamic b) {
  r_assert(
    r_int(a) >= BigInt.zero && r_int(b) > BigInt.zero,
    'remainder domain',
  );
  return a % b;
}

bool r_lt(dynamic a, dynamic b) => r_int(a) < r_int(b);
bool r_not(dynamic a) => !r_bool(a);
bool r_and(dynamic a, dynamic b) {
  final aa = r_bool(a), bb = r_bool(b);
  return aa && bb;
}

bool r_or(dynamic a, dynamic b) {
  final aa = r_bool(a), bb = r_bool(b);
  return aa || bb;
}

String r_kind(dynamic x) {
  if (x == null) return 'null';
  if (x is bool) return 'bool';
  if (x is BigInt) return 'int';
  if (x is String) return 'text';
  if (x is Uint8List) return 'bytes';
  if (x is List) return 'list';
  return 'other';
}

bool r_eq(dynamic a, dynamic b) {
  const kinds = ['null', 'bool', 'int', 'text', 'bytes'];
  r_assert(
    kinds.contains(r_kind(a)) && kinds.contains(r_kind(b)),
    'equality requires scalar operands',
  );
  if (r_kind(a) != r_kind(b)) return false;
  if (a is Uint8List) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
  return a == b;
}

BigInt r_length(dynamic x) {
  r_assert(x is List, 'length requires list or bytes');
  return BigInt.from(x.length);
}

int r_index(dynamic i, int length, [bool end = false]) {
  r_assert(
    r_int(i) >= BigInt.zero &&
        (end ? i <= BigInt.from(length) : i < BigInt.from(length)),
    'index out of bounds',
  );
  return i.toInt();
}

dynamic r_get(dynamic x, dynamic i) {
  r_assert(x is List, 'index requires list or bytes');
  final n = r_index(i, x.length);
  return x is Uint8List ? BigInt.from(x[n]) : x[n];
}

void r_put(dynamic x, dynamic i, dynamic v) {
  r_list(x)[r_index(i, x.length)] = v;
}

List<dynamic> r_slice(dynamic x, dynamic a, dynamic b) {
  r_list(x);
  r_assert(r_int(b) >= r_int(a), 'slice out of bounds');
  return x.sublist(r_index(a, x.length, true), r_index(b, x.length, true));
}

Uint8List r_bytes_slice(dynamic x, dynamic a, dynamic b) {
  r_bytes(x);
  r_assert(r_int(b) >= r_int(a), 'byte slice out of bounds');
  return Uint8List.fromList(
    x.sublist(r_index(a, x.length, true), r_index(b, x.length, true)),
  );
}

List<dynamic> r_reverse(dynamic x) => r_list(x).reversed.toList();
List<dynamic> r_take_last(dynamic x, dynamic n) {
  r_list(x);
  final count = r_index(n, x.length, true);
  final start = x.length - count;
  final out = x.sublist(start);
  x.removeRange(start, x.length);
  return out;
}

dynamic r_pop(dynamic x) {
  r_assert(r_list(x).isNotEmpty, 'pop empty list');
  return x.removeLast();
}

void r_append(dynamic x, dynamic v) {
  r_list(x).add(v);
}

void r_extend(dynamic x, dynamic ys) {
  r_list(x).addAll(List<dynamic>.of(r_list(ys)));
}

Uint8List r_octets(dynamic x) => Uint8List.fromList(
  r_list(x).map<int>((n) {
    r_assert(
      r_int(n) >= BigInt.zero && n <= BigInt.from(255),
      'octet out of range',
    );
    return n.toInt();
  }).toList(),
);
Uint8List r_flatten(dynamic x) {
  final pending = <dynamic>[x], out = BytesBuilder(copy: false);
  while (pending.isNotEmpty) {
    final v = pending.removeLast();
    if (v is Uint8List) {
      out.add(v);
    } else {
      pending.addAll(r_list(v).reversed);
    }
  }
  return out.takeBytes();
}

List<dynamic> r_text_points(dynamic x) {
  final out = <dynamic>[];
  final units = r_text(x).codeUnits;
  for (var i = 0; i < units.length; i++) {
    var c = units[i];
    if (c >= 0xd800 && c <= 0xdbff) {
      r_assert(++i < units.length, 'invalid Unicode scalar');
      final d = units[i];
      r_assert(d >= 0xdc00 && d <= 0xdfff, 'invalid Unicode scalar');
      c = 0x10000 + ((c - 0xd800) << 10) + d - 0xdc00;
    } else {
      r_assert(c < 0xdc00 || c > 0xdfff, 'invalid Unicode scalar');
    }
    out.add(BigInt.from(c));
  }
  return out;
}

String r_points_text(dynamic x) => String.fromCharCodes(
  r_list(x).map<int>((c) {
    r_int(c);
    r_assert(
      c >= BigInt.zero &&
          c <= BigInt.from(0x10ffff) &&
          (c < BigInt.from(0xd800) || c > BigInt.from(0xdfff)),
      'invalid Unicode scalar',
    );
    return c.toInt();
  }),
);
String r_text_join(dynamic xs, dynamic sep) =>
    r_list(xs).map(r_text).join(r_text(sep));
Uint8List r_utf8(dynamic x) {
  r_text_points(x);
  return Uint8List.fromList(utf8.encode(x));
}

List<dynamic> r_utf8_read(dynamic x) {
  r_bytes(x);
  try {
    // Dart's decoder strips an initial BOM; the vocabulary preserves it.
    final bom = x.length >= 3 && x[0] == 239 && x[1] == 187 && x[2] == 191;
    return <dynamic>[
      true,
      (bom ? '\ufeff' : '') + utf8.decode(x, allowMalformed: false),
    ];
  } on FormatException {
    return <dynamic>[false, ''];
  }
}

BigInt r_decimal(dynamic x) {
  r_text(x);
  final match = RegExp(r'^(?:0|-?[1-9][0-9]*)$').firstMatch(x);
  r_assert(match != null && match.end == x.length, 'invalid integer spelling');
  return BigInt.parse(x);
}

String r_integer_text(dynamic x) => r_int(x).toString();
Uint8List r_unhex(dynamic x) {
  r_text(x);
  final match = RegExp(r'^(?:[0-9a-fA-F]{2})*$').firstMatch(x);
  r_assert(match != null && match.end == x.length, 'invalid hexadecimal bytes');
  return Uint8List.fromList([
    for (var i = 0; i < x.length; i += 2)
      int.parse(x.substring(i, i + 2), radix: 16),
  ]);
}

String r_hex(dynamic x) =>
    r_bytes(x).map((b) => b.toRadixString(16).padLeft(2, '0')).join();
int r_compare_bytes(dynamic a, dynamic b) {
  r_bytes(a);
  r_bytes(b);
  final n = a.length < b.length ? a.length : b.length;
  for (var i = 0; i < n; i++) {
    if (a[i] != b[i]) return a[i] - b[i];
  }
  return a.length - b.length;
}

bool r_bytes_less(dynamic a, dynamic b) => r_compare_bytes(a, b) < 0;
List<dynamic> r_sort_bytes_at(dynamic x, dynamic index) {
  final items = r_list(x);
  final decorated = <List<dynamic>>[];
  for (var i = 0; i < items.length; i++) {
    r_bytes(r_get(r_list(items[i]), index));
    decorated.add([items[i], i]);
  }
  decorated.sort((a, b) {
    final c = r_compare_bytes(r_get(a[0], index), r_get(b[0], index));
    return c != 0 ? c : (a[1] as int).compareTo(b[1] as int);
  });
  return decorated.map((x) => x[0]).toList();
}

final _integer_0 = BigInt.parse("0");
final _integer_1 = BigInt.parse("4");
final _integer_2 = BigInt.parse("10");
final _integer_3 = BigInt.parse("11");
final _integer_4 = BigInt.parse("8");
final _integer_5 = BigInt.parse("2");
final _integer_6 = BigInt.parse("5");
final _integer_7 = BigInt.parse("6");
final _integer_8 = BigInt.parse("7");
final _integer_9 = BigInt.parse("1");
final _integer_10 = BigInt.parse("32");
final _integer_11 = BigInt.parse("12");
final _integer_12 = BigInt.parse("3");
final _integer_13 = BigInt.parse("9");
final _integer_14 = BigInt.parse("48");
final _integer_15 = BigInt.parse("16");
dynamic f_encryption_effect(dynamic v_state, dynamic v_phase, dynamic v_effect) {
    r_put(v_state, _integer_0, v_phase);
    return <dynamic>[v_state, v_effect];
}
dynamic f_encryption_finish(dynamic v_state, dynamic v_result) {
    r_put(v_state, _integer_1, null);
    r_put(v_state, _integer_2, null);
    r_put(v_state, _integer_3, v_result);
    return f_encryption_effect(v_state, "done", v_result);
}
dynamic f_encryption_next(dynamic v_state) {
    if (r_bool(r_eq(r_get(v_state, _integer_4), r_length(r_get(v_state, _integer_5))))) {
        return f_encryption_finish(v_state, <dynamic>["done", <dynamic>["x25519-hkdf-sha256-aes256gcm", r_get(v_state, _integer_6), r_get(v_state, _integer_7), r_get(v_state, _integer_8)]]);
    }
    return f_encryption_effect(v_state, "ephemeral", <dynamic>["x25519-ephemeral", r_get(r_get(r_get(v_state, _integer_5), r_get(v_state, _integer_4)), _integer_9)]);
}
dynamic f_encryption_step(dynamic v_state, dynamic v_event) {
    dynamic v_phase = null;
    dynamic v_salt = null;
    dynamic v_value = null;
    dynamic v_zero = null;
    if (r_bool(r_eq(r_get(v_state, _integer_0), "done"))) {
        return <dynamic>[v_state, r_get(v_state, _integer_3)];
    }
    if (r_bool(r_not(r_eq(r_get(v_event, _integer_0), "ok")))) {
        return f_encryption_finish(v_state, <dynamic>["fail", "crypto", "encryption operation failed or cancelled"]);
    }
    v_phase = r_get(v_state, _integer_0);
    v_value = r_get(v_event, _integer_9);
    v_zero = r_octets(<dynamic>[_integer_0, _integer_0, _integer_0, _integer_0, _integer_0, _integer_0, _integer_0, _integer_0, _integer_0, _integer_0, _integer_0, _integer_0]);
    if (r_bool(r_eq(v_phase, "content"))) {
        r_assert(r_eq(r_length(v_value), _integer_10), "expected 32-byte content key");
        r_put(v_state, _integer_1, v_value);
        return f_encryption_effect(v_state, "nonce", <dynamic>["random-bytes", _integer_11]);
    }
    if (r_bool(r_eq(v_phase, "nonce"))) {
        r_assert(r_eq(r_length(v_value), _integer_11), "expected 12-byte nonce");
        r_put(v_state, _integer_6, v_value);
        return f_encryption_effect(v_state, "payload", <dynamic>["aes256gcm-seal", r_get(v_state, _integer_1), r_get(v_state, _integer_6), r_get(v_state, _integer_9), r_get(v_state, _integer_12)]);
    }
    if (r_bool(r_eq(v_phase, "payload"))) {
        r_put(v_state, _integer_7, v_value);
        return f_encryption_next(v_state);
    }
    if (r_bool(r_eq(v_phase, "ephemeral"))) {
        r_assert(r_eq(r_length(v_value), _integer_5), "expected ephemeral public key and shared secret");
        r_assert(r_and(r_eq(r_length(r_get(v_value, _integer_0)), _integer_10), r_eq(r_length(r_get(v_value, _integer_9)), _integer_10)), "invalid agreement result");
        r_put(v_state, _integer_13, r_get(v_value, _integer_0));
        v_salt = r_flatten(<dynamic>[r_get(v_value, _integer_0), r_get(r_get(r_get(v_state, _integer_5), r_get(v_state, _integer_4)), _integer_9)]);
        return f_encryption_effect(v_state, "wrapping-key", <dynamic>["hkdf-sha256", r_get(v_value, _integer_9), v_salt, r_get(v_state, _integer_11), _integer_10]);
    }
    if (r_bool(r_eq(v_phase, "wrapping-key"))) {
        r_assert(r_eq(r_length(v_value), _integer_10), "expected wrapping key");
        return f_encryption_effect(v_state, "wrap", <dynamic>["aes256gcm-seal", v_value, v_zero, r_get(v_state, _integer_1), r_get(v_state, _integer_12)]);
    }
    if (r_bool(r_eq(v_phase, "wrap"))) {
        r_assert(r_eq(r_length(v_value), _integer_14), "expected authenticated wrapped key");
        r_append(r_get(v_state, _integer_8), <dynamic>[r_get(r_get(r_get(v_state, _integer_5), r_get(v_state, _integer_4)), _integer_0), r_get(v_state, _integer_13), v_value]);
        r_put(v_state, _integer_4, r_add(r_get(v_state, _integer_4), _integer_9));
        return f_encryption_next(v_state);
    }
    if (r_bool(r_eq(v_phase, "agreement"))) {
        r_assert(r_eq(r_length(v_value), _integer_5), "expected public key and shared secret");
        r_assert(r_and(r_eq(r_length(r_get(v_value, _integer_0)), _integer_10), r_eq(r_length(r_get(v_value, _integer_9)), _integer_10)), "invalid agreement result");
        v_salt = r_flatten(<dynamic>[r_get(v_state, _integer_13), r_get(v_value, _integer_0)]);
        return f_encryption_effect(v_state, "opening-key", <dynamic>["hkdf-sha256", r_get(v_value, _integer_9), v_salt, r_get(v_state, _integer_11), _integer_10]);
    }
    if (r_bool(r_eq(v_phase, "opening-key"))) {
        r_assert(r_eq(r_length(v_value), _integer_10), "expected wrapping key");
        return f_encryption_effect(v_state, "unwrap", <dynamic>["aes256gcm-open", v_value, v_zero, r_get(v_state, _integer_2), r_get(v_state, _integer_12)]);
    }
    if (r_bool(r_eq(v_phase, "unwrap"))) {
        r_assert(r_eq(r_length(v_value), _integer_10), "expected content key");
        return f_encryption_effect(v_state, "open", <dynamic>["aes256gcm-open", v_value, r_get(v_state, _integer_6), r_get(v_state, _integer_7), r_get(v_state, _integer_12)]);
    }
    r_assert(r_eq(v_phase, "open"), "unknown seal phase");
    return f_encryption_finish(v_state, <dynamic>["done", v_value]);
}
dynamic f_encryption(dynamic v_input) {
    dynamic v_recipients = null;
    dynamic v_sealed = null;
    dynamic v_seen = null;
    dynamic v_selected = null;
    dynamic v_state = null;
    r_assert(r_lt(_integer_0, r_length(v_input)), "missing sealing command");
    if (r_bool(r_eq(r_get(v_input, _integer_0), "step"))) {
        r_assert(r_eq(r_length(v_input), _integer_12), "expected continuation and event");
        return f_encryption_step(r_get(v_input, _integer_9), r_get(v_input, _integer_5));
    }
    if (r_bool(r_eq(r_get(v_input, _integer_0), "seal"))) {
        r_assert(r_eq(r_length(v_input), _integer_6), "seal requires plaintext, recipients, authenticated data and domain");
        r_assert(r_lt(_integer_0, r_length(r_get(v_input, _integer_1))), "empty encryption domain");
        v_recipients = r_get(v_input, _integer_5);
        r_assert(r_lt(_integer_0, r_length(v_recipients)), "cannot encrypt without recipient devices");
        v_seen = <dynamic>[];
        for (final v_recipient in List<dynamic>.of(r_list(v_recipients))) {
            r_assert(r_eq(r_length(v_recipient), _integer_5), "expected signing key id and agreement key");
            r_assert(r_lt(_integer_0, r_length(r_utf8(r_get(v_recipient, _integer_0)))), "empty recipient id");
            r_assert(r_eq(r_length(r_get(v_recipient, _integer_9)), _integer_10), "expected X25519 public key");
            for (final v_previous in List<dynamic>.of(r_list(v_seen))) {
                r_assert(r_not(r_eq(v_previous, r_get(v_recipient, _integer_0))), "duplicate recipient device");
            }
            r_append(v_seen, r_get(v_recipient, _integer_0));
        }
        v_state = <dynamic>["content", r_get(v_input, _integer_9), v_recipients, r_get(v_input, _integer_12), null, null, null, <dynamic>[], _integer_0, null, null, null, r_get(v_input, _integer_1)];
        return <dynamic>[v_state, <dynamic>["random-bytes", _integer_10]];
    }
    r_assert(r_and(r_eq(r_get(v_input, _integer_0), "open"), r_eq(r_length(v_input), _integer_7)), "open requires sealed payload, recipient id, key handle, authenticated data and domain");
    r_assert(r_lt(_integer_0, r_length(r_get(v_input, _integer_6))), "empty encryption domain");
    v_sealed = r_get(v_input, _integer_9);
    r_assert(r_eq(r_length(v_sealed), _integer_1), "invalid sealed payload");
    r_assert(r_eq(r_get(v_sealed, _integer_0), "x25519-hkdf-sha256-aes256gcm"), "unsupported encryption algorithm");
    r_assert(r_and(r_eq(r_length(r_get(v_sealed, _integer_9)), _integer_11), r_not(r_lt(r_length(r_get(v_sealed, _integer_5)), _integer_15))), "invalid encrypted payload");
    r_assert(r_lt(_integer_0, r_length(r_utf8(r_get(v_input, _integer_5)))), "empty recipient id");
    v_selected = <dynamic>[];
    for (final v_wrap in List<dynamic>.of(r_list(r_get(v_sealed, _integer_12)))) {
        r_assert(r_eq(r_length(v_wrap), _integer_12), "invalid recipient wrap");
        if (r_bool(r_eq(r_get(v_wrap, _integer_0), r_get(v_input, _integer_5)))) {
            r_assert(r_eq(r_length(v_selected), _integer_0), "duplicate recipient wrap");
            v_selected = v_wrap;
        }
    }
    v_state = <dynamic>["agreement", null, null, r_get(v_input, _integer_1), null, r_get(v_sealed, _integer_9), r_get(v_sealed, _integer_5), <dynamic>[], _integer_0, null, null, null, r_get(v_input, _integer_6)];
    if (r_bool(r_eq(r_length(v_selected), _integer_0))) {
        return f_encryption_finish(v_state, <dynamic>["fail", "not-for-you", "no wrap for this device"]);
    }
    r_assert(r_and(r_eq(r_length(r_get(v_selected, _integer_9)), _integer_10), r_eq(r_length(r_get(v_selected, _integer_5)), _integer_14)), "invalid recipient wrap bytes");
    r_put(v_state, _integer_13, r_get(v_selected, _integer_9));
    r_put(v_state, _integer_2, r_get(v_selected, _integer_5));
    return <dynamic>[v_state, <dynamic>["x25519-agree", r_get(v_input, _integer_12), r_get(v_selected, _integer_9)]];
}
dynamic run(dynamic v_input) => f_encryption(v_input);
