// GENERATED by tools/portgen/generate.py; edit the source, never this file. secrets-vault.umsg sha256:cd8d93e85f910ed97473e7f6fea4499f0ca4adc83a018810f6a5269fd84baa13 git-credentials.umsg sha256:8ae4117646d75e9c43e647c9df08a307952f69a367d7f4ceabe08b5094f5850d program-v0.umsg sha256:82dd7a0206510a6728ad7bc2b9e03b773de7da750ebb958a95a769748ac2d448 generate.py sha256:caf6b6d888f36ad8c7d66cbeca4abdc1a4cba871a0621a7ce47fdc2c2a68cf71 runtime.py sha256:ad4c62c4259502960dda02e345bd597a8cee527986d79b8984bcaf475aea7677 runtime.js sha256:9da4d4edaa79fa494f4a28c3f4e8a8102a1ff2c0bf86a978810cd87e2f19d603 dart_backend.py sha256:08d9e62142d235d32510b3928c5a8434c3987d227f889b322d8ca50bc9c5d2a5 runtime.dart sha256:577fea510678de6fa07388622a03ee6e13905bf40278f12b03f5ba0b08289327 java_backend.py sha256:e89c9b61a0ba2b5b57d8b4c1bc5bea64c3e84226a0005671eaa1189d645bcf34 runtime.java sha256:bd88f7d7e3d6cb9bfd7831e72c96d5867e995b108da4b48eca67de0d6c2ad411 rust_backend.py sha256:39d06b7d61ce55884f90cced7fe80803a03c1efe970f395a71ace6ea5975ccfc runtime.rs sha256:4080c448093ace2c59859b2bd04d662d9432352fad3385b8d0b17f61f987066d c_backend.py sha256:f359a011e0ad905eade42e07a1b58f278b4f067f095cf050b27e6bc7cae94287 runtime.c sha256:09a74b5b1dd416bb6f0d2b03414ba7888c882be907304f58d9eafb7cc4b3c25e csharp_backend.py sha256:66a83d78353cacaf5f8ffc3b636cc967b6c5e885b0d383061a2bf83910510a08 runtime.cs sha256:98bd7660f26dd2ff5638c91f76fb6f19feaeda0e62a4a2ef181b33441df66ad5
// ignore_for_file: non_constant_identifier_names, unused_element, unused_local_variable, unnecessary_parenthesis
// General operations for the executable vocabulary; no UniMSG rules.
import 'dart:convert';
import 'dart:typed_data';

class ProgramError implements Exception {
  final String message;
  final BigInt offset;
  ProgramError(this.message, this.offset);
  @override
  String toString() => '$message at offset $offset';
}

void r_assert(dynamic test, dynamic message) {
  r_text(message);
  if (!r_bool(test)) throw ArgumentError(message);
}

void r_require(dynamic test, dynamic message, dynamic offset) {
  r_assert(r_int(offset) >= BigInt.zero, 'negative diagnostic offset');
  r_text(message);
  if (!r_bool(test)) throw ProgramError(message, offset);
}

BigInt r_int(dynamic x) {
  if (x is! BigInt) throw ArgumentError('expected integer');
  return x;
}

bool r_bool(dynamic x) {
  if (x is! bool) throw ArgumentError('expected boolean');
  return x;
}

List<dynamic> r_list(dynamic x) {
  if (x is! List || x is Uint8List) throw ArgumentError('expected list');
  return x;
}

String r_text(dynamic x) {
  if (x is! String) throw ArgumentError('expected text');
  return x;
}

Uint8List r_bytes(dynamic x) {
  if (x is! Uint8List) throw ArgumentError('expected bytes');
  return x;
}

dynamic r_add(dynamic a, dynamic b) => r_int(a) + r_int(b);
dynamic r_sub(dynamic a, dynamic b) => r_int(a) - r_int(b);
dynamic r_mul(dynamic a, dynamic b) => r_int(a) * r_int(b);
dynamic r_div(dynamic a, dynamic b) {
  r_assert(
    r_int(a) >= BigInt.zero && r_int(b) > BigInt.zero,
    'division domain',
  );
  return a ~/ b;
}

dynamic r_mod(dynamic a, dynamic b) {
  r_assert(
    r_int(a) >= BigInt.zero && r_int(b) > BigInt.zero,
    'remainder domain',
  );
  return a % b;
}

bool r_lt(dynamic a, dynamic b) => r_int(a) < r_int(b);
bool r_not(dynamic a) => !r_bool(a);
bool r_and(dynamic a, dynamic b) {
  final aa = r_bool(a), bb = r_bool(b);
  return aa && bb;
}

bool r_or(dynamic a, dynamic b) {
  final aa = r_bool(a), bb = r_bool(b);
  return aa || bb;
}

String r_kind(dynamic x) {
  if (x == null) return 'null';
  if (x is bool) return 'bool';
  if (x is BigInt) return 'int';
  if (x is String) return 'text';
  if (x is Uint8List) return 'bytes';
  if (x is List) return 'list';
  return 'other';
}

bool r_eq(dynamic a, dynamic b) {
  const kinds = ['null', 'bool', 'int', 'text', 'bytes'];
  r_assert(
    kinds.contains(r_kind(a)) && kinds.contains(r_kind(b)),
    'equality requires scalar operands',
  );
  if (r_kind(a) != r_kind(b)) return false;
  if (a is Uint8List) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
  return a == b;
}

BigInt r_length(dynamic x) {
  r_assert(x is List, 'length requires list or bytes');
  return BigInt.from(x.length);
}

int r_index(dynamic i, int length, [bool end = false]) {
  r_assert(
    r_int(i) >= BigInt.zero &&
        (end ? i <= BigInt.from(length) : i < BigInt.from(length)),
    'index out of bounds',
  );
  return i.toInt();
}

dynamic r_get(dynamic x, dynamic i) {
  r_assert(x is List, 'index requires list or bytes');
  final n = r_index(i, x.length);
  return x is Uint8List ? BigInt.from(x[n]) : x[n];
}

void r_put(dynamic x, dynamic i, dynamic v) {
  r_list(x)[r_index(i, x.length)] = v;
}

List<dynamic> r_slice(dynamic x, dynamic a, dynamic b) {
  r_list(x);
  r_assert(r_int(b) >= r_int(a), 'slice out of bounds');
  return x.sublist(r_index(a, x.length, true), r_index(b, x.length, true));
}

Uint8List r_bytes_slice(dynamic x, dynamic a, dynamic b) {
  r_bytes(x);
  r_assert(r_int(b) >= r_int(a), 'byte slice out of bounds');
  return Uint8List.fromList(
    x.sublist(r_index(a, x.length, true), r_index(b, x.length, true)),
  );
}

List<dynamic> r_reverse(dynamic x) => r_list(x).reversed.toList();
List<dynamic> r_take_last(dynamic x, dynamic n) {
  r_list(x);
  final count = r_index(n, x.length, true);
  final start = x.length - count;
  final out = x.sublist(start);
  x.removeRange(start, x.length);
  return out;
}

dynamic r_pop(dynamic x) {
  r_assert(r_list(x).isNotEmpty, 'pop empty list');
  return x.removeLast();
}

void r_append(dynamic x, dynamic v) {
  r_list(x).add(v);
}

void r_extend(dynamic x, dynamic ys) {
  r_list(x).addAll(List<dynamic>.of(r_list(ys)));
}

Uint8List r_octets(dynamic x) => Uint8List.fromList(
  r_list(x).map<int>((n) {
    r_assert(
      r_int(n) >= BigInt.zero && n <= BigInt.from(255),
      'octet out of range',
    );
    return n.toInt();
  }).toList(),
);
Uint8List r_flatten(dynamic x) {
  final pending = <dynamic>[x], out = BytesBuilder(copy: false);
  while (pending.isNotEmpty) {
    final v = pending.removeLast();
    if (v is Uint8List) {
      out.add(v);
    } else {
      pending.addAll(r_list(v).reversed);
    }
  }
  return out.takeBytes();
}

List<dynamic> r_text_points(dynamic x) {
  final out = <dynamic>[];
  final units = r_text(x).codeUnits;
  for (var i = 0; i < units.length; i++) {
    var c = units[i];
    if (c >= 0xd800 && c <= 0xdbff) {
      r_assert(++i < units.length, 'invalid Unicode scalar');
      final d = units[i];
      r_assert(d >= 0xdc00 && d <= 0xdfff, 'invalid Unicode scalar');
      c = 0x10000 + ((c - 0xd800) << 10) + d - 0xdc00;
    } else {
      r_assert(c < 0xdc00 || c > 0xdfff, 'invalid Unicode scalar');
    }
    out.add(BigInt.from(c));
  }
  return out;
}

String r_points_text(dynamic x) => String.fromCharCodes(
  r_list(x).map<int>((c) {
    r_int(c);
    r_assert(
      c >= BigInt.zero &&
          c <= BigInt.from(0x10ffff) &&
          (c < BigInt.from(0xd800) || c > BigInt.from(0xdfff)),
      'invalid Unicode scalar',
    );
    return c.toInt();
  }),
);
String r_text_join(dynamic xs, dynamic sep) =>
    r_list(xs).map(r_text).join(r_text(sep));
Uint8List r_utf8(dynamic x) {
  r_text_points(x);
  return Uint8List.fromList(utf8.encode(x));
}

List<dynamic> r_utf8_read(dynamic x) {
  r_bytes(x);
  try {
    // Dart's decoder strips an initial BOM; the vocabulary preserves it.
    final bom = x.length >= 3 && x[0] == 239 && x[1] == 187 && x[2] == 191;
    return <dynamic>[
      true,
      (bom ? '\ufeff' : '') + utf8.decode(x, allowMalformed: false),
    ];
  } on FormatException {
    return <dynamic>[false, ''];
  }
}

BigInt r_decimal(dynamic x) {
  r_text(x);
  final match = RegExp(r'^(?:0|-?[1-9][0-9]*)$').firstMatch(x);
  r_assert(match != null && match.end == x.length, 'invalid integer spelling');
  return BigInt.parse(x);
}

String r_integer_text(dynamic x) => r_int(x).toString();
Uint8List r_unhex(dynamic x) {
  r_text(x);
  // A LOOP AND NOT A PATTERN: a document's bytes can be megabytes of hex, and
  // a regular expression over that overflows the stack.
  final String t = x;
  r_assert(t.length % 2 == 0, 'invalid hexadecimal bytes');
  int digit(int c) => c >= 48 && c <= 57
      ? c - 48
      : c >= 97 && c <= 102
          ? c - 87
          : c >= 65 && c <= 70
              ? c - 55
              : -1;
  final out = Uint8List(t.length ~/ 2);
  for (var i = 0; i < t.length; i += 2) {
    final hi = digit(t.codeUnitAt(i)), lo = digit(t.codeUnitAt(i + 1));
    r_assert(hi >= 0 && lo >= 0, 'invalid hexadecimal bytes');
    out[i ~/ 2] = hi * 16 + lo;
  }
  return out;
}

String r_hex(dynamic x) =>
    r_bytes(x).map((b) => b.toRadixString(16).padLeft(2, '0')).join();
int r_compare_bytes(dynamic a, dynamic b) {
  r_bytes(a);
  r_bytes(b);
  final n = a.length < b.length ? a.length : b.length;
  for (var i = 0; i < n; i++) {
    if (a[i] != b[i]) return a[i] - b[i];
  }
  return a.length - b.length;
}

bool r_bytes_less(dynamic a, dynamic b) => r_compare_bytes(a, b) < 0;
List<dynamic> r_sort_bytes_at(dynamic x, dynamic index) {
  final items = r_list(x);
  final decorated = <List<dynamic>>[];
  for (var i = 0; i < items.length; i++) {
    r_bytes(r_get(r_list(items[i]), index));
    decorated.add([items[i], i]);
  }
  decorated.sort((a, b) {
    final c = r_compare_bytes(r_get(a[0], index), r_get(b[0], index));
    return c != 0 ? c : (a[1] as int).compareTo(b[1] as int);
  });
  return decorated.map((x) => x[0]).toList();
}

final _integer_0 = BigInt.parse("0");
final _integer_1 = BigInt.parse("1");
final _integer_2 = BigInt.parse("4");
final _integer_3 = BigInt.parse("2");
final _integer_4 = BigInt.parse("3");
final _integer_5 = BigInt.parse("10");
final _integer_6 = BigInt.parse("13");
dynamic f_secret_field(dynamic v_fields, dynamic v_name) {
    for (final v_field in List<dynamic>.of(r_list(v_fields))) {
        if (r_bool(r_eq(r_get(v_field, _integer_0), v_name))) {
            return r_get(v_field, _integer_1);
        }
    }
    return "";
}
dynamic f_secrets_validate(dynamic v_records) {
    dynamic v_ids = null;
    dynamic v_label_bytes = null;
    dynamic v_names = null;
    dynamic v_value_bytes = null;
    v_ids = <dynamic>[];
    for (final v_record in List<dynamic>.of(r_list(v_records))) {
        r_assert(r_eq(r_length(v_record), _integer_2), "Invalid secret record");
        r_assert(r_and(r_lt(_integer_0, r_length(r_utf8(r_get(v_record, _integer_0)))), r_lt(_integer_0, r_length(r_utf8(r_get(v_record, _integer_1))))), "Missing secret identity or kind");
        v_label_bytes = r_utf8(r_get(v_record, _integer_3));
        for (final v_identity in List<dynamic>.of(r_list(v_ids))) {
            r_assert(r_not(r_eq(v_identity, r_get(v_record, _integer_0))), "Duplicate secret identity");
        }
        r_append(v_ids, r_get(v_record, _integer_0));
        v_names = <dynamic>[];
        for (final v_field in List<dynamic>.of(r_list(r_get(v_record, _integer_4)))) {
            r_assert(r_eq(r_length(v_field), _integer_3), "Invalid secret field");
            r_assert(r_lt(_integer_0, r_length(r_utf8(r_get(v_field, _integer_0)))), "Empty field name");
            v_value_bytes = r_utf8(r_get(v_field, _integer_1));
            for (final v_name in List<dynamic>.of(r_list(v_names))) {
                r_assert(r_not(r_eq(v_name, r_get(v_field, _integer_0))), "Duplicate secret field");
            }
            r_append(v_names, r_get(v_field, _integer_0));
        }
    }
    return true;
}
dynamic f_secrets_vault(dynamic v_input) {
    dynamic v_identity = null;
    dynamic v_labels = null;
    dynamic v_operation = null;
    dynamic v_output = null;
    dynamic v_records = null;
    dynamic v_valid = null;
    dynamic v_valid_new = null;
    v_operation = r_get(v_input, _integer_0);
    v_records = r_get(v_input, _integer_1);
    v_valid = f_secrets_validate(v_records);
    if (r_bool(r_eq(v_operation, "check"))) {
        return v_records;
    }
    if (r_bool(r_eq(v_operation, "list"))) {
        v_labels = <dynamic>[];
        for (final v_record in List<dynamic>.of(r_list(v_records))) {
            r_append(v_labels, <dynamic>[r_get(v_record, _integer_0), r_get(v_record, _integer_1), r_get(v_record, _integer_3)]);
        }
        return v_labels;
    }
    if (r_bool(r_eq(v_operation, "get"))) {
        for (final v_record in List<dynamic>.of(r_list(v_records))) {
            if (r_bool(r_eq(r_get(v_record, _integer_0), r_get(v_input, _integer_3)))) {
                return v_record;
            }
        }
        return <dynamic>[];
    }
    v_output = <dynamic>[];
    r_assert(r_or(r_eq(v_operation, "put"), r_eq(v_operation, "erase")), "Unknown vault operation");
    v_identity = r_get(v_input, _integer_3);
    if (r_bool(r_eq(v_operation, "put"))) {
        v_valid_new = f_secrets_validate(<dynamic>[r_get(v_input, _integer_3)]);
        v_identity = r_get(r_get(v_input, _integer_3), _integer_0);
    }
    for (final v_record in List<dynamic>.of(r_list(v_records))) {
        if (r_bool(r_not(r_eq(r_get(v_record, _integer_0), v_identity)))) {
            r_append(v_output, v_record);
        }
    }
    if (r_bool(r_eq(v_operation, "put"))) {
        r_append(v_output, r_get(v_input, _integer_3));
    }
    return v_output;
}
dynamic f_git_safe(dynamic v_value) {
    for (final v_point in List<dynamic>.of(r_list(r_text_points(v_value)))) {
        r_assert(r_and(r_and(r_not(r_eq(v_point, _integer_0)), r_not(r_eq(v_point, _integer_5))), r_not(r_eq(v_point, _integer_6))), "Invalid Git credential value");
    }
    return true;
}
dynamic f_git_context(dynamic v_fields, dynamic v_query) {
    return r_and(r_and(r_eq(f_secret_field(v_fields, "protocol"), f_secret_field(v_query, "protocol")), r_eq(f_secret_field(v_fields, "host"), f_secret_field(v_query, "host"))), r_eq(f_secret_field(v_fields, "path"), f_secret_field(v_query, "path")));
}
dynamic f_git_credentials(dynamic v_input) {
    dynamic v_fields = null;
    dynamic v_identity = null;
    dynamic v_matches = null;
    dynamic v_operation = null;
    dynamic v_password = null;
    dynamic v_query = null;
    dynamic v_query_valid = null;
    dynamic v_records = null;
    dynamic v_remaining = null;
    dynamic v_result = null;
    dynamic v_safe = null;
    dynamic v_safe_result = null;
    dynamic v_updated = null;
    dynamic v_username = null;
    dynamic v_valid = null;
    dynamic v_value = null;
    v_operation = r_get(v_input, _integer_0);
    v_records = r_get(v_input, _integer_1);
    v_query = r_get(v_input, _integer_3);
    v_valid = f_secrets_validate(v_records);
    v_query_valid = f_secrets_validate(<dynamic>[<dynamic>["request", "request", "", v_query]]);
    for (final v_field in List<dynamic>.of(r_list(v_query))) {
        v_safe = f_git_safe(r_get(v_field, _integer_1));
    }
    r_assert(r_or(r_or(r_eq(v_operation, "get"), r_eq(v_operation, "store")), r_eq(v_operation, "erase")), "Unknown Git operation");
    if (r_bool(r_or(r_not(r_eq(f_secret_field(v_query, "protocol"), "https")), r_eq(f_secret_field(v_query, "host"), "")))) {
        return <dynamic>[v_records, <dynamic>[]];
    }
    if (r_bool(r_or(r_not(r_eq(f_secret_field(v_query, "authtype"), "")), r_not(r_eq(f_secret_field(v_query, "password_expiry_utc"), ""))))) {
        return <dynamic>[v_records, <dynamic>[]];
    }
    v_username = f_secret_field(v_query, "username");
    v_password = f_secret_field(v_query, "password");
    v_matches = <dynamic>[];
    for (final v_record in List<dynamic>.of(r_list(v_records))) {
        if (r_bool(r_and(r_eq(r_get(v_record, _integer_1), "git-https"), f_git_context(r_get(v_record, _integer_4), v_query)))) {
            if (r_bool(r_or(r_eq(v_username, ""), r_eq(f_secret_field(r_get(v_record, _integer_4), "username"), v_username)))) {
                r_append(v_matches, v_record);
            }
        }
    }
    if (r_bool(r_eq(v_operation, "get"))) {
        if (r_bool(r_not(r_eq(r_length(v_matches), _integer_1)))) {
            return <dynamic>[v_records, <dynamic>[]];
        }
        v_result = <dynamic>[];
        for (final v_key in List<dynamic>.of(r_list(<dynamic>["username", "password"]))) {
            v_value = f_secret_field(r_get(r_get(v_matches, _integer_0), _integer_4), v_key);
            v_safe_result = f_git_safe(v_value);
            r_append(v_result, <dynamic>[v_key, v_value]);
        }
        return <dynamic>[v_records, v_result];
    }
    if (r_bool(r_eq(v_operation, "store"))) {
        if (r_bool(r_or(r_eq(v_username, ""), r_eq(v_password, "")))) {
            return <dynamic>[v_records, <dynamic>[]];
        }
        v_identity = r_get(v_input, _integer_4);
        if (r_bool(r_lt(_integer_0, r_length(v_matches)))) {
            v_identity = r_get(r_get(v_matches, _integer_0), _integer_0);
        }
        v_fields = <dynamic>[];
        for (final v_key in List<dynamic>.of(r_list(<dynamic>["protocol", "host", "path", "username", "password"]))) {
            r_append(v_fields, <dynamic>[v_key, f_secret_field(v_query, v_key)]);
        }
        v_updated = v_records;
        for (final v_matched in List<dynamic>.of(r_list(v_matches))) {
            v_updated = f_secrets_vault(<dynamic>["erase", v_updated, r_get(v_matched, _integer_0)]);
        }
        v_updated = f_secrets_vault(<dynamic>["put", v_updated, <dynamic>[v_identity, "git-https", f_secret_field(v_query, "host"), v_fields]]);
        return <dynamic>[v_updated, <dynamic>[]];
    }
    v_remaining = v_records;
    for (final v_matched in List<dynamic>.of(r_list(v_matches))) {
        if (r_bool(r_or(r_eq(v_password, ""), r_eq(f_secret_field(r_get(v_matched, _integer_4), "password"), v_password)))) {
            v_remaining = f_secrets_vault(<dynamic>["erase", v_remaining, r_get(v_matched, _integer_0)]);
        }
    }
    return <dynamic>[v_remaining, <dynamic>[]];
}
dynamic run(dynamic v_input) => f_git_credentials(v_input);
