// GENERATED by tools/portgen/generate.py; edit the source, never this file. secrets-vault.umsg sha256:cd8d93e85f910ed97473e7f6fea4499f0ca4adc83a018810f6a5269fd84baa13 binary.umsg sha256:e98172988ed1b9c7054d8d6e814b8376714bd8ca69582f602989f140c994b0eb encoder.umsg sha256:09d4bf8168d2a40e536b3afd7bda660faf48047353b8cae2b873cbbaefacbe08 tags.umsg sha256:4e2cfbaefeaa8f1bd25c14fd33502bf0cc1f9f60a101752eb728f4380d648d46 decoder.umsg sha256:d596678eec90ca681be647e4f936e05e4e22bb409927b5f40804d4c7d1fb6619 vault-storage.umsg sha256:9f53e254b225116a04b8a868ae066a15458ef9262adec3a4113128f90e77fdf7 program-v0.umsg sha256:82dd7a0206510a6728ad7bc2b9e03b773de7da750ebb958a95a769748ac2d448 generate.py sha256:caf6b6d888f36ad8c7d66cbeca4abdc1a4cba871a0621a7ce47fdc2c2a68cf71 runtime.py sha256:ad4c62c4259502960dda02e345bd597a8cee527986d79b8984bcaf475aea7677 runtime.js sha256:9da4d4edaa79fa494f4a28c3f4e8a8102a1ff2c0bf86a978810cd87e2f19d603 dart_backend.py sha256:08d9e62142d235d32510b3928c5a8434c3987d227f889b322d8ca50bc9c5d2a5 runtime.dart sha256:577fea510678de6fa07388622a03ee6e13905bf40278f12b03f5ba0b08289327 java_backend.py sha256:e89c9b61a0ba2b5b57d8b4c1bc5bea64c3e84226a0005671eaa1189d645bcf34 runtime.java sha256:bd88f7d7e3d6cb9bfd7831e72c96d5867e995b108da4b48eca67de0d6c2ad411 rust_backend.py sha256:39d06b7d61ce55884f90cced7fe80803a03c1efe970f395a71ace6ea5975ccfc runtime.rs sha256:4080c448093ace2c59859b2bd04d662d9432352fad3385b8d0b17f61f987066d c_backend.py sha256:f359a011e0ad905eade42e07a1b58f278b4f067f095cf050b27e6bc7cae94287 runtime.c sha256:09a74b5b1dd416bb6f0d2b03414ba7888c882be907304f58d9eafb7cc4b3c25e csharp_backend.py sha256:66a83d78353cacaf5f8ffc3b636cc967b6c5e885b0d383061a2bf83910510a08 runtime.cs sha256:98bd7660f26dd2ff5638c91f76fb6f19feaeda0e62a4a2ef181b33441df66ad5
// ignore_for_file: non_constant_identifier_names, unused_element, unused_local_variable, unnecessary_parenthesis
// General operations for the executable vocabulary; no UniMSG rules.
import 'dart:convert';
import 'dart:typed_data';

class ProgramError implements Exception {
  final String message;
  final BigInt offset;
  ProgramError(this.message, this.offset);
  @override
  String toString() => '$message at offset $offset';
}

void r_assert(dynamic test, dynamic message) {
  r_text(message);
  if (!r_bool(test)) throw ArgumentError(message);
}

void r_require(dynamic test, dynamic message, dynamic offset) {
  r_assert(r_int(offset) >= BigInt.zero, 'negative diagnostic offset');
  r_text(message);
  if (!r_bool(test)) throw ProgramError(message, offset);
}

BigInt r_int(dynamic x) {
  if (x is! BigInt) throw ArgumentError('expected integer');
  return x;
}

bool r_bool(dynamic x) {
  if (x is! bool) throw ArgumentError('expected boolean');
  return x;
}

List<dynamic> r_list(dynamic x) {
  if (x is! List || x is Uint8List) throw ArgumentError('expected list');
  return x;
}

String r_text(dynamic x) {
  if (x is! String) throw ArgumentError('expected text');
  return x;
}

Uint8List r_bytes(dynamic x) {
  if (x is! Uint8List) throw ArgumentError('expected bytes');
  return x;
}

dynamic r_add(dynamic a, dynamic b) => r_int(a) + r_int(b);
dynamic r_sub(dynamic a, dynamic b) => r_int(a) - r_int(b);
dynamic r_mul(dynamic a, dynamic b) => r_int(a) * r_int(b);
dynamic r_div(dynamic a, dynamic b) {
  r_assert(
    r_int(a) >= BigInt.zero && r_int(b) > BigInt.zero,
    'division domain',
  );
  return a ~/ b;
}

dynamic r_mod(dynamic a, dynamic b) {
  r_assert(
    r_int(a) >= BigInt.zero && r_int(b) > BigInt.zero,
    'remainder domain',
  );
  return a % b;
}

bool r_lt(dynamic a, dynamic b) => r_int(a) < r_int(b);
bool r_not(dynamic a) => !r_bool(a);
bool r_and(dynamic a, dynamic b) {
  final aa = r_bool(a), bb = r_bool(b);
  return aa && bb;
}

bool r_or(dynamic a, dynamic b) {
  final aa = r_bool(a), bb = r_bool(b);
  return aa || bb;
}

String r_kind(dynamic x) {
  if (x == null) return 'null';
  if (x is bool) return 'bool';
  if (x is BigInt) return 'int';
  if (x is String) return 'text';
  if (x is Uint8List) return 'bytes';
  if (x is List) return 'list';
  return 'other';
}

bool r_eq(dynamic a, dynamic b) {
  const kinds = ['null', 'bool', 'int', 'text', 'bytes'];
  r_assert(
    kinds.contains(r_kind(a)) && kinds.contains(r_kind(b)),
    'equality requires scalar operands',
  );
  if (r_kind(a) != r_kind(b)) return false;
  if (a is Uint8List) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }
    return true;
  }
  return a == b;
}

BigInt r_length(dynamic x) {
  r_assert(x is List, 'length requires list or bytes');
  return BigInt.from(x.length);
}

int r_index(dynamic i, int length, [bool end = false]) {
  r_assert(
    r_int(i) >= BigInt.zero &&
        (end ? i <= BigInt.from(length) : i < BigInt.from(length)),
    'index out of bounds',
  );
  return i.toInt();
}

dynamic r_get(dynamic x, dynamic i) {
  r_assert(x is List, 'index requires list or bytes');
  final n = r_index(i, x.length);
  return x is Uint8List ? BigInt.from(x[n]) : x[n];
}

void r_put(dynamic x, dynamic i, dynamic v) {
  r_list(x)[r_index(i, x.length)] = v;
}

List<dynamic> r_slice(dynamic x, dynamic a, dynamic b) {
  r_list(x);
  r_assert(r_int(b) >= r_int(a), 'slice out of bounds');
  return x.sublist(r_index(a, x.length, true), r_index(b, x.length, true));
}

Uint8List r_bytes_slice(dynamic x, dynamic a, dynamic b) {
  r_bytes(x);
  r_assert(r_int(b) >= r_int(a), 'byte slice out of bounds');
  return Uint8List.fromList(
    x.sublist(r_index(a, x.length, true), r_index(b, x.length, true)),
  );
}

List<dynamic> r_reverse(dynamic x) => r_list(x).reversed.toList();
List<dynamic> r_take_last(dynamic x, dynamic n) {
  r_list(x);
  final count = r_index(n, x.length, true);
  final start = x.length - count;
  final out = x.sublist(start);
  x.removeRange(start, x.length);
  return out;
}

dynamic r_pop(dynamic x) {
  r_assert(r_list(x).isNotEmpty, 'pop empty list');
  return x.removeLast();
}

void r_append(dynamic x, dynamic v) {
  r_list(x).add(v);
}

void r_extend(dynamic x, dynamic ys) {
  r_list(x).addAll(List<dynamic>.of(r_list(ys)));
}

Uint8List r_octets(dynamic x) => Uint8List.fromList(
  r_list(x).map<int>((n) {
    r_assert(
      r_int(n) >= BigInt.zero && n <= BigInt.from(255),
      'octet out of range',
    );
    return n.toInt();
  }).toList(),
);
Uint8List r_flatten(dynamic x) {
  final pending = <dynamic>[x], out = BytesBuilder(copy: false);
  while (pending.isNotEmpty) {
    final v = pending.removeLast();
    if (v is Uint8List) {
      out.add(v);
    } else {
      pending.addAll(r_list(v).reversed);
    }
  }
  return out.takeBytes();
}

List<dynamic> r_text_points(dynamic x) {
  final out = <dynamic>[];
  final units = r_text(x).codeUnits;
  for (var i = 0; i < units.length; i++) {
    var c = units[i];
    if (c >= 0xd800 && c <= 0xdbff) {
      r_assert(++i < units.length, 'invalid Unicode scalar');
      final d = units[i];
      r_assert(d >= 0xdc00 && d <= 0xdfff, 'invalid Unicode scalar');
      c = 0x10000 + ((c - 0xd800) << 10) + d - 0xdc00;
    } else {
      r_assert(c < 0xdc00 || c > 0xdfff, 'invalid Unicode scalar');
    }
    out.add(BigInt.from(c));
  }
  return out;
}

String r_points_text(dynamic x) => String.fromCharCodes(
  r_list(x).map<int>((c) {
    r_int(c);
    r_assert(
      c >= BigInt.zero &&
          c <= BigInt.from(0x10ffff) &&
          (c < BigInt.from(0xd800) || c > BigInt.from(0xdfff)),
      'invalid Unicode scalar',
    );
    return c.toInt();
  }),
);
String r_text_join(dynamic xs, dynamic sep) =>
    r_list(xs).map(r_text).join(r_text(sep));
Uint8List r_utf8(dynamic x) {
  r_text_points(x);
  return Uint8List.fromList(utf8.encode(x));
}

List<dynamic> r_utf8_read(dynamic x) {
  r_bytes(x);
  try {
    // Dart's decoder strips an initial BOM; the vocabulary preserves it.
    final bom = x.length >= 3 && x[0] == 239 && x[1] == 187 && x[2] == 191;
    return <dynamic>[
      true,
      (bom ? '\ufeff' : '') + utf8.decode(x, allowMalformed: false),
    ];
  } on FormatException {
    return <dynamic>[false, ''];
  }
}

BigInt r_decimal(dynamic x) {
  r_text(x);
  final match = RegExp(r'^(?:0|-?[1-9][0-9]*)$').firstMatch(x);
  r_assert(match != null && match.end == x.length, 'invalid integer spelling');
  return BigInt.parse(x);
}

String r_integer_text(dynamic x) => r_int(x).toString();
Uint8List r_unhex(dynamic x) {
  r_text(x);
  // A LOOP AND NOT A PATTERN: a document's bytes can be megabytes of hex, and
  // a regular expression over that overflows the stack.
  final String t = x;
  r_assert(t.length % 2 == 0, 'invalid hexadecimal bytes');
  int digit(int c) => c >= 48 && c <= 57
      ? c - 48
      : c >= 97 && c <= 102
          ? c - 87
          : c >= 65 && c <= 70
              ? c - 55
              : -1;
  final out = Uint8List(t.length ~/ 2);
  for (var i = 0; i < t.length; i += 2) {
    final hi = digit(t.codeUnitAt(i)), lo = digit(t.codeUnitAt(i + 1));
    r_assert(hi >= 0 && lo >= 0, 'invalid hexadecimal bytes');
    out[i ~/ 2] = hi * 16 + lo;
  }
  return out;
}

String r_hex(dynamic x) =>
    r_bytes(x).map((b) => b.toRadixString(16).padLeft(2, '0')).join();
int r_compare_bytes(dynamic a, dynamic b) {
  r_bytes(a);
  r_bytes(b);
  final n = a.length < b.length ? a.length : b.length;
  for (var i = 0; i < n; i++) {
    if (a[i] != b[i]) return a[i] - b[i];
  }
  return a.length - b.length;
}

bool r_bytes_less(dynamic a, dynamic b) => r_compare_bytes(a, b) < 0;
List<dynamic> r_sort_bytes_at(dynamic x, dynamic index) {
  final items = r_list(x);
  final decorated = <List<dynamic>>[];
  for (var i = 0; i < items.length; i++) {
    r_bytes(r_get(r_list(items[i]), index));
    decorated.add([items[i], i]);
  }
  decorated.sort((a, b) {
    final c = r_compare_bytes(r_get(a[0], index), r_get(b[0], index));
    return c != 0 ? c : (a[1] as int).compareTo(b[1] as int);
  });
  return decorated.map((x) => x[0]).toList();
}

final _integer_0 = BigInt.parse("0");
final _integer_1 = BigInt.parse("1");
final _integer_2 = BigInt.parse("4");
final _integer_3 = BigInt.parse("2");
final _integer_4 = BigInt.parse("3");
final _integer_5 = BigInt.parse("256");
final _integer_6 = BigInt.parse("10");
final _integer_7 = BigInt.parse("15");
final _integer_8 = BigInt.parse("31");
final _integer_9 = BigInt.parse("23");
final _integer_10 = BigInt.parse("127");
final _integer_11 = BigInt.parse("255");
final _integer_12 = BigInt.parse("8");
final _integer_13 = BigInt.parse("52");
final _integer_14 = BigInt.parse("1023");
final _integer_15 = BigInt.parse("2047");
final _integer_16 = BigInt.parse("11");
final _integer_17 = BigInt.parse("24");
final _integer_18 = BigInt.parse("249");
final _integer_19 = BigInt.parse("250");
final _integer_20 = BigInt.parse("251");
final _integer_21 = BigInt.parse("4096");
final _integer_22 = BigInt.parse("32");
final _integer_23 = BigInt.parse("27");
final _integer_24 = BigInt.parse("65536");
final _integer_25 = BigInt.parse("25");
final _integer_26 = BigInt.parse("4294967296");
final _integer_27 = BigInt.parse("26");
final _integer_28 = BigInt.parse("-1");
final _integer_29 = BigInt.parse("18446744073709551616");
final _integer_30 = BigInt.parse("6");
final _integer_31 = BigInt.parse("246");
final _integer_32 = BigInt.parse("244");
final _integer_33 = BigInt.parse("245");
final _integer_34 = BigInt.parse("5");
final _integer_35 = BigInt.parse("70107");
final _integer_36 = BigInt.parse("40");
final _integer_37 = BigInt.parse("64");
final _integer_38 = BigInt.parse("65");
final _integer_39 = BigInt.parse("66");
final _integer_40 = BigInt.parse("67");
final _integer_41 = BigInt.parse("72");
final _integer_42 = BigInt.parse("73");
final _integer_43 = BigInt.parse("74");
final _integer_44 = BigInt.parse("75");
final _integer_45 = BigInt.parse("80");
final _integer_46 = BigInt.parse("81");
final _integer_47 = BigInt.parse("82");
final _integer_48 = BigInt.parse("7");
final _integer_49 = BigInt.parse("88");
final _integer_50 = BigInt.parse("1040");
final _integer_51 = BigInt.parse("70100");
final _integer_52 = BigInt.parse("70102");
final _integer_53 = BigInt.parse("70103");
final _integer_54 = BigInt.parse("70106");
final _integer_55 = BigInt.parse("70104");
final _integer_56 = BigInt.parse("70105");
final _integer_57 = BigInt.parse("70101");
final _integer_58 = BigInt.parse("28");
final _integer_59 = BigInt.parse("20");
final _integer_60 = BigInt.parse("22");
final _integer_61 = BigInt.parse("21");
dynamic f_secret_field(dynamic v_fields, dynamic v_name) {
    for (final v_field in List<dynamic>.of(r_list(v_fields))) {
        if (r_bool(r_eq(r_get(v_field, _integer_0), v_name))) {
            return r_get(v_field, _integer_1);
        }
    }
    return "";
}
dynamic f_secrets_validate(dynamic v_records) {
    dynamic v_ids = null;
    dynamic v_label_bytes = null;
    dynamic v_names = null;
    dynamic v_value_bytes = null;
    v_ids = <dynamic>[];
    for (final v_record in List<dynamic>.of(r_list(v_records))) {
        r_assert(r_eq(r_length(v_record), _integer_2), "Invalid secret record");
        r_assert(r_and(r_lt(_integer_0, r_length(r_utf8(r_get(v_record, _integer_0)))), r_lt(_integer_0, r_length(r_utf8(r_get(v_record, _integer_1))))), "Missing secret identity or kind");
        v_label_bytes = r_utf8(r_get(v_record, _integer_3));
        for (final v_identity in List<dynamic>.of(r_list(v_ids))) {
            r_assert(r_not(r_eq(v_identity, r_get(v_record, _integer_0))), "Duplicate secret identity");
        }
        r_append(v_ids, r_get(v_record, _integer_0));
        v_names = <dynamic>[];
        for (final v_field in List<dynamic>.of(r_list(r_get(v_record, _integer_4)))) {
            r_assert(r_eq(r_length(v_field), _integer_3), "Invalid secret field");
            r_assert(r_lt(_integer_0, r_length(r_utf8(r_get(v_field, _integer_0)))), "Empty field name");
            v_value_bytes = r_utf8(r_get(v_field, _integer_1));
            for (final v_name in List<dynamic>.of(r_list(v_names))) {
                r_assert(r_not(r_eq(v_name, r_get(v_field, _integer_0))), "Duplicate secret field");
            }
            r_append(v_names, r_get(v_field, _integer_0));
        }
    }
    return true;
}
dynamic f_secrets_vault(dynamic v_input) {
    dynamic v_identity = null;
    dynamic v_labels = null;
    dynamic v_operation = null;
    dynamic v_output = null;
    dynamic v_records = null;
    dynamic v_valid = null;
    dynamic v_valid_new = null;
    v_operation = r_get(v_input, _integer_0);
    v_records = r_get(v_input, _integer_1);
    v_valid = f_secrets_validate(v_records);
    if (r_bool(r_eq(v_operation, "check"))) {
        return v_records;
    }
    if (r_bool(r_eq(v_operation, "list"))) {
        v_labels = <dynamic>[];
        for (final v_record in List<dynamic>.of(r_list(v_records))) {
            r_append(v_labels, <dynamic>[r_get(v_record, _integer_0), r_get(v_record, _integer_1), r_get(v_record, _integer_3)]);
        }
        return v_labels;
    }
    if (r_bool(r_eq(v_operation, "get"))) {
        for (final v_record in List<dynamic>.of(r_list(v_records))) {
            if (r_bool(r_eq(r_get(v_record, _integer_0), r_get(v_input, _integer_3)))) {
                return v_record;
            }
        }
        return <dynamic>[];
    }
    v_output = <dynamic>[];
    r_assert(r_or(r_eq(v_operation, "put"), r_eq(v_operation, "erase")), "Unknown vault operation");
    v_identity = r_get(v_input, _integer_3);
    if (r_bool(r_eq(v_operation, "put"))) {
        v_valid_new = f_secrets_validate(<dynamic>[r_get(v_input, _integer_3)]);
        v_identity = r_get(r_get(v_input, _integer_3), _integer_0);
    }
    for (final v_record in List<dynamic>.of(r_list(v_records))) {
        if (r_bool(r_not(r_eq(r_get(v_record, _integer_0), v_identity)))) {
            r_append(v_output, v_record);
        }
    }
    if (r_bool(r_eq(v_operation, "put"))) {
        r_append(v_output, r_get(v_input, _integer_3));
    }
    return v_output;
}
dynamic f_power_two(dynamic v_n) {
    dynamic v_r = _integer_1;
    while (r_bool(r_lt(_integer_0, v_n))) {
        v_r = r_mul(v_r, _integer_3);
        v_n = r_sub(v_n, _integer_1);
    }
    return v_r;
}
dynamic f_unsigned(dynamic v_data) {
    dynamic v_r = _integer_0;
    dynamic v_i = _integer_0;
    while (r_bool(r_lt(v_i, r_length(v_data)))) {
        v_r = r_add(r_mul(v_r, _integer_5), r_get(v_data, v_i));
        v_i = r_add(v_i, _integer_1);
    }
    return v_r;
}
dynamic f_float_fits(dynamic v_m, dynamic v_e, dynamic v_precision, dynamic v_bias) {
    if (r_bool(r_eq(v_m, _integer_0))) {
        return true;
    }
    while (r_bool(r_eq(r_mod(v_m, _integer_3), _integer_0))) {
        v_m = r_div(v_m, _integer_3);
        v_e = r_add(v_e, _integer_1);
    }
    dynamic v_bits = _integer_0;
    while (r_bool(r_lt(_integer_0, v_m))) {
        v_bits = r_add(v_bits, _integer_1);
        v_m = r_div(v_m, _integer_3);
    }
    if (r_bool(r_lt(v_precision, v_bits))) {
        return false;
    }
    dynamic v_minimum = r_sub(r_sub(_integer_3, v_bias), v_precision);
    if (r_bool(r_lt(v_e, v_minimum))) {
        return false;
    }
    return r_not(r_lt(v_bias, r_sub(r_add(v_e, v_bits), _integer_1)));
}
dynamic f_float_valid(dynamic v_raw, dynamic v_shortest) {
    dynamic v_width = r_length(v_raw);
    dynamic v_fraction_bits = _integer_6;
    dynamic v_bias = _integer_7;
    dynamic v_maximum = _integer_8;
    if (r_bool(r_eq(v_width, _integer_2))) {
        v_fraction_bits = _integer_9;
        v_bias = _integer_10;
        v_maximum = _integer_11;
    }
    if (r_bool(r_eq(v_width, _integer_12))) {
        v_fraction_bits = _integer_13;
        v_bias = _integer_14;
        v_maximum = _integer_15;
    }
    if (r_bool(r_not(r_or(r_eq(v_width, _integer_3), r_or(r_eq(v_width, _integer_2), r_eq(v_width, _integer_12)))))) {
        return false;
    }
    dynamic v_u = f_unsigned(v_raw);
    dynamic v_scale = f_power_two(v_fraction_bits);
    dynamic v_fraction = r_mod(v_u, v_scale);
    dynamic v_exponent = r_mod(r_div(v_u, v_scale), r_add(v_maximum, _integer_1));
    if (r_bool(r_eq(v_exponent, v_maximum))) {
        if (r_bool(r_and(v_shortest, r_not(r_eq(v_width, _integer_3))))) {
            return false;
        }
        if (r_bool(r_eq(v_fraction, _integer_0))) {
            return true;
        }
        return r_eq(v_u, r_add(r_mul(v_maximum, v_scale), r_div(v_scale, _integer_3)));
    }
    if (r_bool(r_or(r_not(v_shortest), r_eq(v_width, _integer_3)))) {
        return true;
    }
    dynamic v_m = v_fraction;
    dynamic v_e = r_sub(r_sub(_integer_1, v_bias), v_fraction_bits);
    if (r_bool(r_lt(_integer_0, v_exponent))) {
        v_m = r_add(v_m, v_scale);
        v_e = r_sub(r_sub(v_exponent, v_bias), v_fraction_bits);
    }
    dynamic v_precision = _integer_16;
    dynamic v_target_bias = _integer_7;
    if (r_bool(r_eq(v_width, _integer_12))) {
        v_precision = _integer_17;
        v_target_bias = _integer_10;
    }
    return r_not(f_float_fits(v_m, v_e, v_precision, v_target_bias));
}
dynamic f_float_encoding(dynamic v_node) {
    r_assert(r_eq(r_length(v_node), _integer_4), "float node arity");
    dynamic v_label = r_get(v_node, _integer_1);
    dynamic v_width = _integer_0;
    dynamic v_header = _integer_0;
    if (r_bool(r_eq(v_label, "f16"))) {
        v_width = _integer_3;
        v_header = _integer_18;
    }
    if (r_bool(r_eq(v_label, "f32"))) {
        v_width = _integer_2;
        v_header = _integer_19;
    }
    if (r_bool(r_eq(v_label, "f64"))) {
        v_width = _integer_12;
        v_header = _integer_20;
    }
    r_assert(r_lt(_integer_0, v_width), "unsupported float width");
    dynamic v_raw = r_unhex(r_get(v_node, _integer_3));
    r_assert(r_eq(r_length(v_raw), v_width), "float payload width");
    r_assert(f_float_valid(v_raw, true), "noncanonical float");
    return <dynamic>[r_octets(<dynamic>[v_header]), v_raw];
}
dynamic f_check_depth(dynamic v_depth) {
    r_assert(r_lt(v_depth, _integer_21), "structural depth limit");
    return null;
}
dynamic f_shape(dynamic v_value, dynamic v_size) {
    r_assert(r_eq(r_kind(v_value), "list"), "node must be a list");
    r_assert(r_eq(r_length(v_value), v_size), "wrong node arity");
    return null;
}
dynamic f_uint_bytes(dynamic v_n, dynamic v_width) {
    dynamic v_out = <dynamic>[];
    dynamic v_i = _integer_0;
    while (r_bool(r_lt(v_i, v_width))) {
        r_append(v_out, r_mod(v_n, _integer_5));
        v_n = r_div(v_n, _integer_5);
        v_i = r_add(v_i, _integer_1);
    }
    r_assert(r_eq(v_n, _integer_0), "unsigned integer does not fit");
    return r_octets(r_reverse(v_out));
}
dynamic f_head(dynamic v_major, dynamic v_n) {
    r_assert(r_not(r_lt(v_n, _integer_0)), "negative header argument");
    dynamic v_base = r_mul(v_major, _integer_22);
    if (r_bool(r_lt(v_n, _integer_17))) {
        return r_octets(<dynamic>[r_add(v_base, v_n)]);
    }
    dynamic v_width = _integer_12;
    dynamic v_info = _integer_23;
    if (r_bool(r_lt(v_n, _integer_5))) {
        v_width = _integer_1;
        v_info = _integer_17;
    }
    else {
        if (r_bool(r_lt(v_n, _integer_24))) {
            v_width = _integer_3;
            v_info = _integer_25;
        }
        else {
            if (r_bool(r_lt(v_n, _integer_26))) {
                v_width = _integer_2;
                v_info = _integer_27;
            }
        }
    }
    return r_flatten(<dynamic>[r_octets(<dynamic>[r_add(v_base, v_info)]), f_uint_bytes(v_n, v_width)]);
}
dynamic f_integer(dynamic v_n) {
    dynamic v_major = _integer_0;
    dynamic v_tag = _integer_3;
    if (r_bool(r_lt(v_n, _integer_0))) {
        v_major = _integer_1;
        v_tag = _integer_4;
        v_n = r_sub(_integer_28, v_n);
    }
    if (r_bool(r_lt(v_n, _integer_29))) {
        return f_head(v_major, v_n);
    }
    dynamic v_digits = <dynamic>[];
    while (r_bool(r_lt(_integer_0, v_n))) {
        r_append(v_digits, r_mod(v_n, _integer_5));
        v_n = r_div(v_n, _integer_5);
    }
    return r_flatten(<dynamic>[f_head(_integer_30, v_tag), f_head(_integer_3, r_length(v_digits)), r_octets(r_reverse(v_digits))]);
}
dynamic f_encode(dynamic v_value) {
    dynamic v_jobs = <dynamic>[<dynamic>["visit", v_value, _integer_0]];
    dynamic v_results = <dynamic>[];
    while (r_bool(r_lt(_integer_0, r_length(v_jobs)))) {
        dynamic v_job = r_pop(v_jobs);
        dynamic v_action = r_get(v_job, _integer_0);
        if (r_bool(r_eq(v_action, "visit"))) {
            dynamic v_node = r_get(v_job, _integer_1);
            dynamic v_depth = r_get(v_job, _integer_3);
            r_assert(r_eq(r_kind(v_node), "list"), "node must be a list");
            r_assert(r_lt(_integer_0, r_length(v_node)), "empty node");
            dynamic v_kind = r_get(v_node, _integer_0);
            r_assert(r_eq(r_kind(v_kind), "text"), "node kind must be text");
            dynamic v_handled = false;
            if (r_bool(r_eq(v_kind, "float"))) {
                r_append(v_results, f_float_encoding(v_node));
                v_handled = true;
            }
            if (r_bool(r_eq(v_kind, "null"))) {
                dynamic v_checked = f_shape(v_node, _integer_1);
                r_append(v_results, r_octets(<dynamic>[_integer_31]));
                v_handled = true;
            }
            if (r_bool(r_eq(v_kind, "bool"))) {
                dynamic v_checked = f_shape(v_node, _integer_3);
                dynamic v_b = r_get(v_node, _integer_1);
                dynamic v_octet = _integer_32;
                if (r_bool(v_b)) {
                    v_octet = _integer_33;
                }
                r_append(v_results, r_octets(<dynamic>[v_octet]));
                v_handled = true;
            }
            if (r_bool(r_eq(v_kind, "int"))) {
                dynamic v_checked = f_shape(v_node, _integer_3);
                r_append(v_results, f_integer(r_decimal(r_get(v_node, _integer_1))));
                v_handled = true;
            }
            if (r_bool(r_eq(v_kind, "text"))) {
                dynamic v_checked = f_shape(v_node, _integer_3);
                dynamic v_data = r_utf8(r_get(v_node, _integer_1));
                r_append(v_results, <dynamic>[f_head(_integer_4, r_length(v_data)), v_data]);
                v_handled = true;
            }
            if (r_bool(r_eq(v_kind, "bytes"))) {
                dynamic v_checked = f_shape(v_node, _integer_3);
                dynamic v_data = r_unhex(r_get(v_node, _integer_1));
                r_append(v_results, <dynamic>[f_head(_integer_3, r_length(v_data)), v_data]);
                v_handled = true;
            }
            if (r_bool(r_eq(v_kind, "seq"))) {
                dynamic v_checked = f_shape(v_node, _integer_3);
                dynamic v_depth_checked = f_check_depth(v_depth);
                dynamic v_children = r_get(v_node, _integer_1);
                r_assert(r_eq(r_kind(v_children), "list"), "sequence payload must be a list");
                r_append(v_jobs, <dynamic>["seq", r_length(v_children)]);
                for (final v_child in List<dynamic>.of(r_list(r_reverse(v_children)))) {
                    r_append(v_jobs, <dynamic>["visit", v_child, r_add(v_depth, _integer_1)]);
                }
                v_handled = true;
            }
            if (r_bool(r_eq(v_kind, "map"))) {
                dynamic v_checked = f_shape(v_node, _integer_3);
                dynamic v_depth_checked = f_check_depth(v_depth);
                dynamic v_pairs = r_get(v_node, _integer_1);
                r_assert(r_eq(r_kind(v_pairs), "list"), "map payload must be a list");
                r_append(v_jobs, <dynamic>["map", r_length(v_pairs)]);
                for (final v_pair in List<dynamic>.of(r_list(r_reverse(v_pairs)))) {
                    dynamic v_checked_pair = f_shape(v_pair, _integer_3);
                    r_append(v_jobs, <dynamic>["visit", r_get(v_pair, _integer_1), r_add(v_depth, _integer_1)]);
                    r_append(v_jobs, <dynamic>["visit", r_get(v_pair, _integer_0), r_add(v_depth, _integer_1)]);
                }
                v_handled = true;
            }
            if (r_bool(r_eq(v_kind, "tagged"))) {
                dynamic v_checked = f_shape(v_node, _integer_4);
                dynamic v_depth_checked = f_check_depth(v_depth);
                dynamic v_tag = r_decimal(r_get(v_node, _integer_1));
                r_assert(r_not(r_eq(v_tag, _integer_3)), "bignum tags require int nodes");
                r_assert(r_not(r_eq(v_tag, _integer_4)), "bignum tags require int nodes");
                dynamic v_header = f_head(_integer_30, v_tag);
                r_append(v_jobs, <dynamic>["tagged", v_header]);
                r_append(v_jobs, <dynamic>["visit", r_get(v_node, _integer_3), r_add(v_depth, _integer_1)]);
                v_handled = true;
            }
            r_assert(v_handled, "unsupported value kind");
        }
        else {
            if (r_bool(r_eq(v_action, "tagged"))) {
                dynamic v_content = r_pop(v_results);
                r_append(v_results, <dynamic>[r_get(v_job, _integer_1), v_content]);
            }
            else {
                dynamic v_count = r_get(v_job, _integer_1);
                dynamic v_slots = v_count;
                if (r_bool(r_eq(v_action, "map"))) {
                    v_slots = r_mul(v_count, _integer_3);
                }
                dynamic v_parts = r_take_last(v_results, v_slots);
                dynamic v_out = <dynamic>[];
                if (r_bool(r_eq(v_action, "seq"))) {
                    r_append(v_out, f_head(_integer_2, v_count));
                    r_extend(v_out, v_parts);
                }
                else {
                    dynamic v_entries = <dynamic>[];
                    dynamic v_i = _integer_0;
                    while (r_bool(r_lt(v_i, r_length(v_parts)))) {
                        r_append(v_entries, <dynamic>[r_flatten(r_get(v_parts, v_i)), r_get(v_parts, r_add(v_i, _integer_1))]);
                        v_i = r_add(v_i, _integer_3);
                    }
                    v_entries = r_sort_bytes_at(v_entries, _integer_0);
                    r_append(v_out, f_head(_integer_34, v_count));
                    dynamic v_previous = null;
                    for (final v_entry in List<dynamic>.of(r_list(v_entries))) {
                        dynamic v_key = r_get(v_entry, _integer_0);
                        r_assert(r_not(r_eq(v_previous, v_key)), "duplicate canonical key");
                        v_previous = v_key;
                        r_extend(v_out, v_entry);
                    }
                }
                r_append(v_results, v_out);
            }
        }
    }
    return r_flatten(r_get(v_results, _integer_0));
}
dynamic f_payload(dynamic v_node, dynamic v_kind, dynamic v_at) {
    r_require(r_eq(r_get(v_node, _integer_0), v_kind), "wrong tag payload kind", v_at);
    return r_get(v_node, _integer_1);
}
dynamic f_two_items(dynamic v_node, dynamic v_at) {
    dynamic v_items = f_payload(v_node, "seq", v_at);
    r_require(r_eq(r_length(v_items), _integer_3), "tag requires two items", v_at);
    return v_items;
}
dynamic f_typed_array(dynamic v_node, dynamic v_at) {
    dynamic v_mask = null;
    dynamic v_dims = null;
    dynamic v_tag = r_decimal(f_payload(v_node, "tagged", v_at));
    if (r_bool(r_eq(v_tag, _integer_35))) {
        dynamic v_items = f_two_items(r_get(v_node, _integer_3), v_at);
        v_mask = r_unhex(f_payload(r_get(v_items, _integer_0), "bytes", v_at));
        v_node = r_get(v_items, _integer_1);
        v_tag = r_decimal(f_payload(v_node, "tagged", v_at));
    }
    if (r_bool(r_eq(v_tag, _integer_36))) {
        dynamic v_items = f_two_items(r_get(v_node, _integer_3), v_at);
        v_dims = f_payload(r_get(v_items, _integer_0), "seq", v_at);
        r_require(r_not(r_lt(r_length(v_dims), _integer_3)), "shape requires at least two extents", v_at);
        v_node = r_get(v_items, _integer_1);
        v_tag = r_decimal(f_payload(v_node, "tagged", v_at));
    }
    dynamic v_width = _integer_0;
    dynamic v_floating = false;
    for (final v_row in List<dynamic>.of(r_list(<dynamic>[<dynamic>[_integer_37, _integer_1, false], <dynamic>[_integer_38, _integer_3, false], <dynamic>[_integer_39, _integer_2, false], <dynamic>[_integer_40, _integer_12, false], <dynamic>[_integer_41, _integer_1, false], <dynamic>[_integer_42, _integer_3, false], <dynamic>[_integer_43, _integer_2, false], <dynamic>[_integer_44, _integer_12, false], <dynamic>[_integer_45, _integer_3, true], <dynamic>[_integer_46, _integer_2, true], <dynamic>[_integer_47, _integer_12, true]]))) {
        if (r_bool(r_eq(r_get(v_row, _integer_0), v_tag))) {
            v_width = r_get(v_row, _integer_1);
            v_floating = r_get(v_row, _integer_3);
        }
    }
    r_require(r_lt(_integer_0, v_width), "unsupported typed-array tag or wrapper order", v_at);
    dynamic v_raw = r_unhex(f_payload(r_get(v_node, _integer_3), "bytes", v_at));
    r_require(r_eq(r_mod(r_length(v_raw), v_width), _integer_0), "partial typed-array element", v_at);
    dynamic v_count = r_div(r_length(v_raw), v_width);
    if (r_bool(v_floating)) {
        dynamic v_i = _integer_0;
        while (r_bool(r_lt(v_i, r_length(v_raw)))) {
            r_require(f_float_valid(r_bytes_slice(v_raw, v_i, r_add(v_i, v_width)), false), "noncanonical typed-array NaN", v_at);
            v_i = r_add(v_i, v_width);
        }
    }
    if (r_bool(r_eq(r_kind(v_dims), "list"))) {
        dynamic v_product = _integer_1;
        for (final v_dimension in List<dynamic>.of(r_list(v_dims))) {
            dynamic v_n = r_decimal(f_payload(v_dimension, "int", v_at));
            r_require(r_not(r_lt(v_n, _integer_0)), "negative extent", v_at);
            v_product = r_mul(v_product, v_n);
        }
        r_require(r_eq(v_product, v_count), "shape does not match element count", v_at);
    }
    if (r_bool(r_eq(r_kind(v_mask), "bytes"))) {
        r_require(r_eq(r_length(v_mask), r_div(r_add(v_count, _integer_48), _integer_12)), "mask length mismatch", v_at);
        dynamic v_present = _integer_0;
        dynamic v_i = _integer_0;
        while (r_bool(r_lt(v_i, v_count))) {
            dynamic v_bit = r_mod(r_div(r_get(v_mask, r_div(v_i, _integer_12)), f_power_two(r_mod(v_i, _integer_12))), _integer_3);
            if (r_bool(r_eq(v_bit, _integer_1))) {
                v_present = r_add(v_present, _integer_1);
            }
            else {
                dynamic v_start = r_mul(v_i, v_width);
                r_require(r_eq(f_unsigned(r_bytes_slice(v_raw, v_start, r_add(v_start, v_width))), _integer_0), "missing element has nonzero bits", v_at);
            }
            v_i = r_add(v_i, _integer_1);
        }
        dynamic v_remainder = r_mod(v_count, _integer_12);
        if (r_bool(r_lt(_integer_0, v_remainder))) {
            r_require(r_eq(r_div(r_get(v_mask, r_sub(r_length(v_mask), _integer_1)), f_power_two(v_remainder)), _integer_0), "nonzero mask padding", v_at);
        }
        r_require(r_lt(v_present, v_count), "redundant validity mask", v_at);
    }
    return null;
}
dynamic f_make_tag(dynamic v_tag, dynamic v_content, dynamic v_at) {
    if (r_bool(r_or(r_eq(v_tag, _integer_3), r_eq(v_tag, _integer_4)))) {
        dynamic v_raw = r_unhex(f_payload(v_content, "bytes", v_at));
        r_require(r_lt(_integer_12, r_length(v_raw)), "bignum fits a basic integer", v_at);
        r_require(r_not(r_eq(r_get(v_raw, _integer_0), _integer_0)), "leading zero in bignum", v_at);
        dynamic v_n = f_unsigned(v_raw);
        if (r_bool(r_eq(v_tag, _integer_4))) {
            v_n = r_sub(_integer_28, v_n);
        }
        return <dynamic>["int", r_integer_text(v_n)];
    }
    dynamic v_node = <dynamic>["tagged", r_integer_text(v_tag), v_content];
    if (r_bool(r_or(r_and(r_not(r_lt(v_tag, _integer_37)), r_lt(v_tag, _integer_49)), r_or(r_eq(v_tag, _integer_36), r_or(r_eq(v_tag, _integer_35), r_eq(v_tag, _integer_50)))))) {
        dynamic v_checked = f_typed_array(v_node, v_at);
    }
    if (r_bool(r_or(r_eq(v_tag, _integer_51), r_or(r_eq(v_tag, _integer_52), r_or(r_eq(v_tag, _integer_53), r_eq(v_tag, _integer_54)))))) {
        dynamic v_checked = f_payload(v_content, "text", v_at);
    }
    if (r_bool(r_eq(v_tag, _integer_2))) {
        dynamic v_items = f_two_items(v_content, v_at);
        for (final v_item in List<dynamic>.of(r_list(v_items))) {
            dynamic v_checked = f_payload(v_item, "int", v_at);
        }
    }
    if (r_bool(r_or(r_eq(v_tag, _integer_55), r_eq(v_tag, _integer_56)))) {
        dynamic v_items = f_two_items(v_content, v_at);
        dynamic v_checked = f_payload(r_get(v_items, _integer_0), "text", v_at);
        if (r_bool(r_eq(v_tag, _integer_55))) {
            dynamic v_checked_digest = f_payload(r_get(v_items, _integer_1), "bytes", v_at);
        }
    }
    if (r_bool(r_eq(v_tag, _integer_57))) {
        dynamic v_items = f_two_items(v_content, v_at);
        dynamic v_annotations = f_payload(r_get(v_items, _integer_0), "seq", v_at);
        for (final v_annotation in List<dynamic>.of(r_list(v_annotations))) {
            dynamic v_number = r_decimal(f_payload(v_annotation, "tagged", v_at));
            r_require(r_or(r_eq(v_number, _integer_51), r_eq(v_number, _integer_52)), "annotation must be a symbol or identifier", v_at);
        }
    }
    return v_node;
}
dynamic f_read_head(dynamic v_data, dynamic v_pos) {
    dynamic v_start = v_pos;
    r_require(r_lt(v_pos, r_length(v_data)), "truncated item head", v_pos);
    dynamic v_byte = r_get(v_data, v_pos);
    dynamic v_major = r_div(v_byte, _integer_22);
    dynamic v_ai = r_mod(v_byte, _integer_22);
    v_pos = r_add(v_pos, _integer_1);
    if (r_bool(r_lt(v_ai, _integer_17))) {
        return <dynamic>[v_major, v_ai, v_pos, v_ai];
    }
    r_require(r_lt(v_ai, _integer_58), "reserved or indefinite additional information", v_start);
    dynamic v_width = f_power_two(r_sub(v_ai, _integer_17));
    r_require(r_not(r_lt(r_sub(r_length(v_data), v_pos), v_width)), "truncated head argument", v_pos);
    dynamic v_end = r_add(v_pos, v_width);
    dynamic v_n = f_unsigned(r_bytes_slice(v_data, v_pos, v_end));
    if (r_bool(r_not(r_eq(v_major, _integer_48)))) {
        dynamic v_minimum = _integer_17;
        if (r_bool(r_lt(_integer_1, v_width))) {
            v_minimum = f_power_two(r_mul(r_div(v_width, _integer_3), _integer_12));
        }
        r_require(r_not(r_lt(v_n, v_minimum)), "nonminimal head", v_start);
    }
    return <dynamic>[v_major, v_n, v_end, v_ai];
}
dynamic f_decode(dynamic v_data) {
    r_require(r_eq(r_kind(v_data), "bytes"), "input must be bytes", _integer_0);
    dynamic v_pos = _integer_0;
    dynamic v_stack = <dynamic>[];
    dynamic v_have = false;
    dynamic v_done = false;
    dynamic v_value = null;
    dynamic v_value_start = _integer_0;
    while (r_bool(r_not(v_done))) {
        if (r_bool(r_not(v_have))) {
            v_value_start = v_pos;
            dynamic v_h = f_read_head(v_data, v_pos);
            dynamic v_major = r_get(v_h, _integer_0);
            dynamic v_n = r_get(v_h, _integer_1);
            v_pos = r_get(v_h, _integer_3);
            dynamic v_ai = r_get(v_h, _integer_4);
            if (r_bool(r_lt(v_major, _integer_3))) {
                if (r_bool(r_eq(v_major, _integer_1))) {
                    v_n = r_sub(_integer_28, v_n);
                }
                v_value = <dynamic>["int", r_integer_text(v_n)];
                v_have = true;
            }
            if (r_bool(r_or(r_eq(v_major, _integer_3), r_eq(v_major, _integer_4)))) {
                r_require(r_not(r_lt(r_sub(r_length(v_data), v_pos), v_n)), "declared string length exceeds remaining bytes", v_pos);
                dynamic v_end = r_add(v_pos, v_n);
                dynamic v_raw = r_bytes_slice(v_data, v_pos, v_end);
                if (r_bool(r_eq(v_major, _integer_3))) {
                    v_value = <dynamic>["bytes", r_hex(v_raw)];
                }
                else {
                    dynamic v_text = r_utf8_read(v_raw);
                    r_require(r_get(v_text, _integer_0), "invalid UTF-8 in text payload", v_pos);
                    v_value = <dynamic>["text", r_get(v_text, _integer_1)];
                }
                v_pos = v_end;
                v_have = true;
            }
            if (r_bool(r_and(r_not(r_lt(v_major, _integer_2)), r_lt(v_major, _integer_48)))) {
                r_require(r_lt(r_length(v_stack), _integer_21), "structural depth limit", v_value_start);
                dynamic v_kind = "seq";
                dynamic v_need = v_n;
                if (r_bool(r_eq(v_major, _integer_34))) {
                    v_kind = "map";
                    v_need = r_mul(v_n, _integer_3);
                }
                if (r_bool(r_eq(v_major, _integer_30))) {
                    v_kind = "tagged";
                    v_need = _integer_1;
                }
                r_require(r_not(r_lt(r_sub(r_length(v_data), v_pos), v_need)), "declared item count exceeds remaining bytes", v_pos);
                if (r_bool(r_eq(v_need, _integer_0))) {
                    v_value = <dynamic>[v_kind, <dynamic>[]];
                    v_have = true;
                }
                else {
                    r_append(v_stack, <dynamic>[v_kind, v_need, <dynamic>[], v_n, v_value_start, <dynamic>[]]);
                }
            }
            if (r_bool(r_eq(v_major, _integer_48))) {
                if (r_bool(r_lt(v_ai, _integer_17))) {
                    r_require(r_and(r_not(r_lt(v_ai, _integer_59)), r_lt(v_ai, _integer_9)), "unsupported simple value", v_value_start);
                    v_value = <dynamic>["null"];
                    if (r_bool(r_lt(v_ai, _integer_60))) {
                        v_value = <dynamic>["bool", r_eq(v_ai, _integer_61)];
                    }
                }
                else {
                    r_require(r_lt(_integer_17, v_ai), "unsupported simple-value form", v_value_start);
                    dynamic v_raw = r_bytes_slice(v_data, r_add(v_value_start, _integer_1), v_pos);
                    r_require(f_float_valid(v_raw, true), "noncanonical float", v_value_start);
                    dynamic v_label = "f16";
                    if (r_bool(r_eq(v_ai, _integer_27))) {
                        v_label = "f32";
                    }
                    if (r_bool(r_eq(v_ai, _integer_23))) {
                        v_label = "f64";
                    }
                    v_value = <dynamic>["float", v_label, r_hex(v_raw)];
                }
                v_have = true;
            }
        }
        while (r_bool(r_and(v_have, r_lt(_integer_0, r_length(v_stack))))) {
            dynamic v_frame = r_get(v_stack, r_sub(r_length(v_stack), _integer_1));
            dynamic v_kind = r_get(v_frame, _integer_0);
            dynamic v_items = r_get(v_frame, _integer_3);
            if (r_bool(r_and(r_eq(v_kind, "map"), r_eq(r_mod(r_length(v_items), _integer_3), _integer_0)))) {
                dynamic v_key_bytes = r_bytes_slice(v_data, v_value_start, v_pos);
                r_append(r_get(v_frame, _integer_34), <dynamic>[v_key_bytes, v_value_start]);
            }
            r_append(v_items, v_value);
            dynamic v_remaining = r_sub(r_get(v_frame, _integer_1), _integer_1);
            r_put(v_frame, _integer_1, v_remaining);
            if (r_bool(r_lt(_integer_0, v_remaining))) {
                v_have = false;
            }
            else {
                dynamic v_removed = r_pop(v_stack);
                v_value_start = r_get(v_frame, _integer_2);
                v_value = <dynamic>["seq", v_items];
                if (r_bool(r_eq(v_kind, "tagged"))) {
                    v_value = f_make_tag(r_get(v_frame, _integer_4), r_get(v_items, _integer_0), v_value_start);
                }
                if (r_bool(r_eq(v_kind, "map"))) {
                    dynamic v_keys = r_sort_bytes_at(r_get(v_frame, _integer_34), _integer_0);
                    dynamic v_previous = null;
                    for (final v_key in List<dynamic>.of(r_list(v_keys))) {
                        r_require(r_not(r_eq(v_previous, r_get(v_key, _integer_0))), "duplicate canonical map key", r_get(v_key, _integer_1));
                        v_previous = r_get(v_key, _integer_0);
                    }
                    dynamic v_pairs = <dynamic>[];
                    dynamic v_i = _integer_0;
                    while (r_bool(r_lt(v_i, r_length(v_items)))) {
                        r_append(v_pairs, <dynamic>[r_get(v_items, v_i), r_get(v_items, r_add(v_i, _integer_1))]);
                        v_i = r_add(v_i, _integer_3);
                    }
                    v_value = <dynamic>["map", v_pairs];
                }
            }
        }
        if (r_bool(r_and(v_have, r_eq(r_length(v_stack), _integer_0)))) {
            v_done = true;
        }
    }
    r_require(r_eq(v_pos, r_length(v_data)), "trailing data", v_pos);
    dynamic v_again = f_encode(v_value);
    dynamic v_i = _integer_0;
    dynamic v_same = true;
    while (r_bool(r_and(v_same, r_and(r_lt(v_i, r_length(v_data)), r_lt(v_i, r_length(v_again)))))) {
        v_same = r_eq(r_get(v_data, v_i), r_get(v_again, v_i));
        if (r_bool(v_same)) {
            v_i = r_add(v_i, _integer_1);
        }
    }
    r_require(r_and(v_same, r_eq(r_length(v_data), r_length(v_again))), "re-encoding differs", v_i);
    return v_value;
}
dynamic f_secrets_node(dynamic v_value) {
    dynamic v_children = null;
    if (r_bool(r_eq(r_kind(v_value), "text"))) {
        return <dynamic>["text", v_value];
    }
    if (r_bool(r_eq(r_kind(v_value), "bytes"))) {
        return <dynamic>["bytes", r_hex(v_value)];
    }
    v_children = <dynamic>[];
    for (final v_child in List<dynamic>.of(r_list(v_value))) {
        r_append(v_children, f_secrets_node(v_child));
    }
    return <dynamic>["seq", v_children];
}
dynamic f_secrets_value(dynamic v_node) {
    dynamic v_children = null;
    if (r_bool(r_eq(r_get(v_node, _integer_0), "text"))) {
        return r_get(v_node, _integer_1);
    }
    if (r_bool(r_eq(r_get(v_node, _integer_0), "bytes"))) {
        return r_unhex(r_get(v_node, _integer_1));
    }
    r_assert(r_eq(r_get(v_node, _integer_0), "seq"), "Invalid secrets value");
    v_children = <dynamic>[];
    for (final v_child in List<dynamic>.of(r_list(r_get(v_node, _integer_1)))) {
        r_append(v_children, f_secrets_value(v_child));
    }
    return v_children;
}
dynamic f_secrets_member(dynamic v_node, dynamic v_name) {
    r_assert(r_eq(r_get(v_node, _integer_0), "map"), "Expected secrets document");
    for (final v_pair in List<dynamic>.of(r_list(r_get(v_node, _integer_1)))) {
        if (r_bool(r_and(r_eq(r_get(r_get(v_pair, _integer_0), _integer_0), "text"), r_eq(r_get(r_get(v_pair, _integer_0), _integer_1), v_name)))) {
            return f_secrets_value(r_get(v_pair, _integer_1));
        }
    }
    r_assert(false, "Missing secrets field");
    return "";
}
dynamic f_vault_storage(dynamic v_input) {
    dynamic v_checked = null;
    dynamic v_key = null;
    dynamic v_node = null;
    dynamic v_payload = null;
    dynamic v_profile = null;
    dynamic v_records = null;
    v_profile = "unimsg/secrets/v0";
    if (r_bool(r_eq(r_get(v_input, _integer_0), "seal"))) {
        v_checked = f_secrets_validate(r_get(v_input, _integer_1));
        v_payload = f_encode(<dynamic>["map", <dynamic>[<dynamic>[<dynamic>["text", "format"], <dynamic>["text", v_profile]], <dynamic>[<dynamic>["text", "records"], f_secrets_node(r_get(v_input, _integer_1))]]]);
        return <dynamic>["seal", v_payload, <dynamic>[<dynamic>[r_get(r_get(v_input, _integer_3), _integer_0), r_get(r_get(v_input, _integer_3), _integer_1)]], r_utf8(v_profile), r_utf8(v_profile)];
    }
    if (r_bool(r_eq(r_get(v_input, _integer_0), "open"))) {
        return <dynamic>["open", r_get(v_input, _integer_1), r_get(v_input, _integer_3), r_get(v_input, _integer_3), r_utf8(v_profile), r_utf8(v_profile)];
    }
    if (r_bool(r_eq(r_get(v_input, _integer_0), "records"))) {
        v_payload = f_decode(r_get(v_input, _integer_1));
        r_assert(r_eq(f_secrets_member(v_payload, "format"), v_profile), "Wrong secret payload");
        v_records = f_secrets_member(v_payload, "records");
        v_checked = f_secrets_validate(v_records);
        return v_records;
    }
    if (r_bool(r_eq(r_get(v_input, _integer_0), "pack"))) {
        return f_encode(<dynamic>["map", <dynamic>[<dynamic>[<dynamic>["text", "format"], <dynamic>["text", "unimsg/os-protected-vault/v0"]], <dynamic>[<dynamic>["text", "custody"], <dynamic>["text", r_get(v_input, _integer_4)]], <dynamic>[<dynamic>["text", "key"], f_secrets_node(r_get(v_input, _integer_1))], <dynamic>[<dynamic>["text", "encrypted"], f_secrets_node(r_get(v_input, _integer_3))]]]);
    }
    r_assert(r_eq(r_get(v_input, _integer_0), "unpack"), "Unknown storage operation");
    v_node = f_decode(r_get(v_input, _integer_1));
    r_assert(r_eq(f_secrets_member(v_node, "format"), "unimsg/os-protected-vault/v0"), "Wrong storage format");
    r_assert(r_eq(f_secrets_member(v_node, "custody"), r_get(v_input, _integer_3)), "Different native key custody");
    v_key = f_secrets_member(v_node, "key");
    r_assert(r_and(r_eq(r_length(v_key), _integer_4), r_eq(r_length(r_get(v_key, _integer_1)), _integer_22)), "Invalid protected key");
    return <dynamic>[v_key, f_secrets_member(v_node, "encrypted")];
}
dynamic run(dynamic v_input) => f_vault_storage(v_input);
